FROM node:lts-alpine

WORKDIR /app

COPY package.json .

RUN yarn install

COPY . .

RUN yarn install

RUN yarn install


## EXPOSE [Port you mentioned in the vite.config file]

EXPOSE 5173

# CMD ["watch","-n","60", "ls"]
CMD ["yarn", "dev","--host=0.0.0.0"]