version: '3'

networks:
  airbnb:

services:
  fe-react:
    build:
      context: ./fe-react
      dockerfile: Dockerfile.react
    ports:
      - "5173:5173"   
    depends_on:
      - db
    volumes:
      - ./fe-react:/app
    networks:
    - airbnb
  api-go:
    build:
      context: ./api-go
      dockerfile: Dockerfile.golang
    ports:
      - "9000:9000"   
    depends_on:
      - db
    volumes:
      - ./api-go:/app
    networks:
    - airbnb
  db:
    volumes:
      - ./fe-react/db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
    - airbnb

       
